### ISSUE TITLE
I m trying to add additional parameter in fulfillBasicOrder but it gives me error

### ISSUE THREAD

**Issue by umeraqeel786** [ProjectOpenSea/seaport#1040]
Hi @seaport community 
When I add additional parameter in fulfillBasicOrder  it gives me error of **InvalidBasicOrderParameterEncoding**

Please help me out how can I add additional parameter in this function as I have less understanding of assembly lang.

@stephankmin  @0age @jameswenzel

**Comment by jecombe** [comment]
you need to encode your params, for exemple in nodejs, pass that to smart contract and decode your params like this: 
`ParamsOpensea memory orderParams = abi.decode(_params, (ParamsOpensea));`
After that, you can fill your order params for fulfillBasicOrder method.
