### ISSUE TITLE
Allow safeTransfer/safeTransferFrom for ERC721

### ISSUE THREAD

**Issue by anajuliabit** [ProjectOpenSea/seaport#1081]
At the moment, only ERC1155 utilizes safe transfer functions. 
Using safeTransfer for ERC721 would be very useful for us, as we need to know the _tokenId exchanged after the order is fulfilled.

**Comment by vishal590** [comment]
@anajuliabit I am unable to run project. I ran command yarn build and got error and also got error for forge library

**Comment by anajuliabit** [comment]
@vishal590 Which project?

**Comment by vishal590** [comment]
@anajuliabit
Project - opensea/seaport

**Comment by anajuliabit** [comment]
this is not the appropriate place to ask for assistance. Have you tried checking out opensea discord?

**Comment by vishal590** [comment]
I tried more times no one answering.
