### ISSUE TITLE
Deployment docs missing instructions for 1.3, 1.4 & 1.5

### ISSUE THREAD

**Issue by oneski** [ProjectOpenSea/seaport#1193]
The deployment docs [here](https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md) only include instructions for 1.1 and 1.2. 

Adding 1.3 and 1.4 would allow for ease in deploying to other networks!

**Comment by oneski** [comment]
updating to include 1.5 :)

**Comment by ryanio** [comment]
The docs are now updated for v1.5 deployment, we only recommend using the latest version.
