### ISSUE TITLE
Release notes and change logs in GitHub release tags

### ISSUE THREAD

**Issue by a6-dou** [ProjectOpenSea/seaport#1233]
Hey, we at TrustWallet are working on an [off-chain SDK](https://github.com/trustwallet/wizard-sdk) that visualize EIP-712 message payload and translate it into a structured data that highlight use asset\s impact so wallets can display a more UX friendly UI and provide better security/economical analysis.

one of the protocols we support is Seaport and we would like to stay up to date with all the changes you guys make, can you please point where can we see what changed in v1.5 so we can update our implementation also? 

If you want to know more about the SDK:
- [source code](https://github.com/trustwallet/wizard-sdk)
- [EIP-6865](https://github.com/ethereum/EIPs/pull/6865)
- [Workshop Presentation](https://www.youtube.com/live/cH_apck7rqI?feature=share&t=1069)

Thanks!

**Comment by a6-dou** [comment]
Update: after some search i found the blog post and 0age tweet regarding the 1.5 release as explained in this [PR](https://github.com/trustwallet/wizard-sdk/pull/23).

Indeed, it would be nicer if we have the same details in the [release tag](https://github.com/ProjectOpenSea/seaport/releases/tag/1.5)

**Comment by ryanio** [comment]
@a6-dou it's a great point, thanks for raising. this link can also help you compare the diffs in the future between tags: https://github.com/ProjectOpenSea/seaport/compare/1.4...1.5
