### ISSUE TITLE
【Criteria-based orders】how to fufill criteria-based order when i want to buy two or more tokenid from merkletree ？

### ISSUE THREAD

**Issue by bwhour** [ProjectOpenSea/seaport#1245]
<img width="1042" alt="image" src="https://github.com/ProjectOpenSea/seaport/assets/8485901/d7182ce4-d3cb-4e48-9d1f-6a74546366dd">

Hi, seaport-team, if i want to buy the two tokenids in criteria-based order in one fullfillAdvancedOrder, how should i write the paramter ? when i wrote like this, it revert with _revertCriteriaNotEnabledForItem

*it("Criteria-based offer item ERC721 (standard)", async () => {
      // Seller mints nfts
      const [nftId, secondNFTId, thirdNFTId] = await mint721s(seller, 3);

      const tokenIds = [nftId, secondNFTId, thirdNFTId];

      // Seller approves marketplace contract to transfer NFTs
      await set721ApprovalForAll(seller, marketplaceContract.address, true);

      const { root, proofs } = merkleTree(tokenIds);
      console.log("merkleRoot : " + root);
      const offer = [getTestItem721WithCriteria(root, toBN(2), toBN(2))];

      const consideration = [
        getItemETH(parseEther("10"), parseEther("10"), seller.address),
        getItemETH(parseEther("1"), parseEther("1"), zone.address),
        getItemETH(parseEther("1"), parseEther("1"), owner.address),
      ];

      const criteriaResolvers = [
        buildResolver(0, 0, 0, secondNFTId, proofs[secondNFTId.toString()]),
        buildResolver(0, 0, 0, thirdNFTId, proofs[thirdNFTId.toString()]),
      ];*

**Comment by bwhour** [comment]
the criteriaResolvers with  one  buildResolver， it works.  but i want to buy secondNFTId  and thirdNFTId , how to fill  them ?

**Comment by ryanio** [comment]
you have to increment orderIndex

**Comment by bwhour** [comment]
> increment

orderIndex is related to  offer Items, currently there is only one offer. the orderIndex should be zero.

**Comment by ryanio** [comment]
oh only one order? ok then you have to increment the item index in the resolver
