### ISSUE TITLE
changelog file

### ISSUE THREAD

**Issue by GopherJ** [ProjectOpenSea/seaport#1248]
currently seems we need to go to @0age 's twitter to know the changes between each version, can we maintain a changelog file instead?

**Comment by PaulRBerg** [comment]
Yes, please. In Sablier V2, we are using [Common Changelog](https://common-changelog.org/):

- https://github.com/sablier-labs/v2-core/blob/main/CHANGELOG.md
- https://github.com/sablier-labs/v2-periphery/blob/main/CHANGELOG.md

**Comment by PaulRBerg** [comment]
this issue should remain open IMO
