### ISSUE TITLE
Does the source code for the Web Interface exist?

### ISSUE THREAD

**Issue by alexbakers** [ProjectOpenSea/seaport#1255]
Hello.

Seaport is deployed in many networks, but on Opensea only polygon and ethereum.

Does the source code for the Web Interface exist? 
Or what is the point of a new network if there is no web interface to interact with it?
 
Thx.

**Comment by yangwao** [comment]
Hey we plan to integrate seaport in KodaDot pretty soon.

https://github.com/kodadot/nft-gallery

**Comment by alexbakers** [comment]
> Hey we plan to integrate seaport in KodaDot pretty soon.
> 
> https://github.com/kodadot/nft-gallery

I look forward to it, thank you.

**Comment by ryanio** [comment]
The OpenSea supported chains are listed here: https://docs.opensea.io/reference/supported-chains
