### ISSUE TITLE
Support OpenZeppelin Forwarder on Seaport for gasless experience

### ISSUE THREAD

**Issue by JOY** [ProjectOpenSea/seaport#1275]
Hi team,

We plan to provide the gasless experience to our users on our NFT Marketplace using seaport. I'd like to ask how can we support OpenZeppelin Forwarder?

Link: 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/metatx/ERC2771Forwarder.sol

Docs:
https://docs.openzeppelin.com/contracts/4.x/api/metatx#MinimalForwarder

**Comment by AnhDOS** [comment]
Any update please?

**Comment by JOY** [comment]
Bump
