### ISSUE TITLE
 Contract wallet WalletConnect : Internal server error occurred

### ISSUE THREAD

**Issue by Yonghengl** [ProjectOpenSea/seaport#1276]
When I use the contract wallet(Loopring Wallet ,argent, ambire) to connect https://opensea.io/, this interface appears after the connection is successful
<img width="459" alt="image" src="https://github.com/ProjectOpenSea/seaport/assets/55374358/9d71fd0d-7d98-43eb-9ac6-e213186beb04">
After the wallet is signed, an error occurs
<img width="684" alt="image" src="https://github.com/ProjectOpenSea/seaport/assets/55374358/b12d0070-72ad-423f-9d77-61596e829fa3">
<img width="549" alt="image" src="https://github.com/ProjectOpenSea/seaport/assets/55374358/19b14d5a-8e47-453f-940c-86e86fedafaa">

**Comment by ryanio** [comment]
This repository is for Seaport the marketplace contract, for OpenSea support please open a ticket at https://support.opensea.io/hc/en-us
