### ISSUE TITLE
INFO - Seaport 1.5 Deploy on Astar

### ISSUE THREAD

**Issue by bruck93** [ProjectOpenSea/seaport#1279]
Hi,
I'm looking to deploy Seaport 1.5 on Astar network.

I took a look at the docs here ( https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md ) and are clear.

The only thing that I noticed is that, on Astar, some addresses are already took by some EVM accounts, like the conduit address ( https://astar.subscan.io/account/0x00000000F9490004C11Cef243f5400493c00Ad63 ).

What is the best way to move Seaport there, to avoid mistakes ?

Thanks.

**Comment by montasaurus** [comment]
Not very familiar with Astar, but what are you seeing that indicates it was taken? Not seeing any transactions (even though the nonce is apparently at 2 already). If it's following regular EVM rules, something else wouldn't be able to take the conduit's address

**Comment by bruck93** [comment]
Hey @montasaurus I was able to find some other infos on another blockscan and I noticed that the conduit controller seems already deployed there ( https://blockscout.com/astar/address/0x00000000F9490004C11Cef243f5400493c00Ad63/internal-transactions#address-tabs ).

Took me sometime, I'll eventually update you.
Thanks

**Comment by sharadjaiswal1411** [comment]
Any update on this, I  facing same issue on pulsechain addresses are already there, I am able to list an NFT , but not able to buy, 
Getting error 
![Screenshot 2023-10-08 044926](https://github.com/ProjectOpenSea/seaport/assets/7452657/4d685991-146d-47b6-85f5-9bdb78d9e4e1)
