### ISSUE TITLE
Error while deploying `CREATE2 DEPLOYER`

### ISSUE THREAD

**Issue by eugenioclrc** [ProjectOpenSea/seaport#1281]
Hello! im trying to deploy the create2 deployer on this RPC `https://rpc1.mainnet.lachain.network`. I have prefunded  `0x4c8D290a1B368ac4728d83a9e8321fC3af2b39b1`, but im having this issue;
```sh
(base) ➜  LAC  cast publish 0xf87e8085174876e800830186a08080ad601f80600e600039806000f350fe60003681823780368234f58015156014578182fd5b80825250506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222 --rpc-url https://rpc1.mainnet.lachain.network                                           
Error: 
(code: -32600, message: transaction underpriced, data: None)
```

Anyone know whats going on?

**Comment by atarapra** [comment]
I am also fetching issue for create2 deployer on `holseky` testnet. but given pre-sign msg is not `EIP-155` format.
```
✗ cast publish 0xf87e8085174876e800830186a08080ad601f80600e600039806000f350fe60003681823780368234f58015156014578182fd5b80825250506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222 --rpc-url $holesky_rpc
Error: 
(code: -32000, message: only replay-protected (EIP-155) transactions allowed over RPC, data: None)
``` 
@0age can you update pre-signed msg for `KEYLESS_CREATE2_DEPLOYER_ADDRESS`.

**Comment by eugenioclrc** [comment]
Quick update on this, the chain where im trying to deploy the `CREATE2DEPLOYER` has a fixed gas price of 5000 GWEI, making the tx underpriced :(

Gas bad, lachain bad...

<img width="245" alt="image" src="https://github.com/ProjectOpenSea/seaport/assets/332426/7adf371e-c570-468b-95c5-189ffdd4d4e6">

Im gonna close this, @atarapra encourage you to open a new issue with your bug.
