### ISSUE TITLE
Cast error issue: (code: -32000, message: only replay-protected (EIP-155) transactions allowed over RPC, data: None)

### ISSUE THREAD

**Issue by Fluffynorth** [ProjectOpenSea/seaport#1303]
$ cast publish --rpc-url https://rpc.phoenixplorer.com 0xf87e8085174876e800830186a08080ad601f80600e600039806000f350fe60003681823780368234f58015156014578182fd5b80825250506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222
Error:
(code: -32000, message: only replay-protected (EIP-155) transactions allowed over RPC, data: None)

**Comment by Fluffynorth** [comment]
Figured it out

**Comment by ryanio** [comment]
you need to get access to a RPC node that will send your transaction without checking EIP-155 replay protection. would get in touch with the chain you are trying to do this on and ask if they can help.
