### ISSUE TITLE
Seaport 1.6 Failed to deploy contract using provided salt and initialization code

### ISSUE THREAD

**Issue by Fluffynorth** [ProjectOpenSea/seaport#1316]
(code: 3, message: execution reverted: Failed to deploy contract using provided salt and initialization code., data: Some(String("0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000464661696c656420746f206465706c6f7920636f6e7472616374207573696e672070726f76696465642073616c7420616e6420696e697469616c697a6174696f6e20636f64652e0000000000000000000000000000000000000000000000000000")))

**Comment by ryanio** [comment]
This usually means you don't have sufficient funds or the contract is already deployed

**Comment by Fluffynorth** [comment]
@ryanio v1.5 has been deployed and I added plenty of funds but still getting the same error

**Comment by ryanio** [comment]
which chain are you trying to deploy to

**Comment by Fluffynorth** [comment]
Phoenix

**Comment by Fluffynorth** [comment]
aside from verifying a few contracts we are nearly there only having issues with seaport bytecode not matching when verifying, even tried verifying using sourcify but it has the same problem everything else verified properly https://phoenixplorer.com/address/0x0000000000FFe8B47B3e2130213B802212439497/transactions

**Comment by ryanio** [comment]
make sure you provide the constructor args for verification: `00000000000000000000000000000000f9490004c11cef243f5400493c00ad63`

**Comment by Fluffynorth** [comment]
@ryanio where it says Ensure that EXPLORER_API_KEY and NETWORK_RPC are set in .env appropriately. If there is no api key is it ok to leave out of .env or EXPLORER_API_KEY =

**Comment by sunnybinb** [comment]
I meet the same error and it was not caused by "not enough gas"  and "contract has been deployed"

**Comment by ahmedshehzadBiM** [comment]
> I met the same error and it was not caused by "not enough gas" and "contract has been deployed"

I am stuck with the same error, can you guide how your error was resolved?

**Comment by georgeroman** [comment]
This is probably coming from the chain you're deploying to not supporting the `PUSH0` opcode, which the canonical Seaport 1.6 deployment uses. You can either wait until the chain adds support for `PUSH0` or can compile Seaport 1.6 such that it doesn't use `PUSH0`.
