### ISSUE TITLE
SeaportValidator checks the wrong ID for ZoneInterface

### ISSUE THREAD

**Issue by mchmatt** [ProjectOpenSea/seaport#1327]
# Description
ZONE_INTERFACE_ID here is 0x3839be19, set over an year ago: https://github.com/ProjectOpenSea/seaport/blob/refs/tags/1.6/contracts/helpers/order-validator/SeaportValidator.sol#L94

But ZoneInterface was changed when Seaport 1.6 released: https://github.com/ProjectOpenSea/seaport-types/commit/ff1be8a17993af2a1f09a2f7b1fc8767d8dbe95f#diff-f69614cada94e5766ae0ec37ec5d01c05060c5afd5fff569771b5cc61cd7ff16 

This produces an InvalidZone warning as a result; is it safe to ignore that warning? Or should we wait for SeaportValidator to be updated to 1.6 before migrating to it?

# Notes
I submitted this on Discord under #seaport-education; submitting here so patch/discussion is more easily accessible to everyone

**Comment by 0age** [comment]
The zone check is pretty broken on the validator contract even before considering this one; depending on the type of zone (which ideally the validator would detect) you'd either need to supply the right extraData (which should be pretty straightforward for fixed data like dynamic trait validation params) or build in some special-casing into the zone in cases where you don't even have the extraData you need at the moment, like for the SignedZone (one option here could be to build zones that just return the magic value if `tx.origin == address(0)`).

Another good thing to include would be for the validator to try calling this method on the zone on the order, throwing the warning if the method's not available or doesn't implement an SIP: https://github.com/ProjectOpenSea/SIPs/blob/main/SIPS/sip-5.md

This is a good callout though, there are no immediate plans to deploy a new validator so you'll probably want to ignore these warnings for the time being and encourage anyone interested to put up a PR with a fix for the function selector or even some of these other improvements!

**Comment by YummyCoin** [comment]
Thank You for letting me be apart of something Great!!! Coding and Community... I can't wait to see where this project goes, too the galaxy and beyond !!!
