### ISSUE TITLE
Payout Wallet Selector

### ISSUE THREAD

**Issue by Matlemad** [ProjectOpenSea/seaport#1342]
As an owner of a corporate multisig, I need to be able to create collections easily from my EOA but set the payout wallet of a Collection' sales to the company's one.

unleash NFTs again, help publishing collectives.

**Comment by ryanio** [comment]
in seaport orders you can set the recipient of the consideration items to any address, however opensea will enforce it being the "offerer" as part of order validation. if you are taking about creator fees, seaport doesn't have any built in, but in marketplaces like opensea you can set the payout address for a collection to any wallet in the settings of the collection. hope this answered your questions.
