### ISSUE TITLE
Foundry tests require optimized profile

### ISSUE THREAD

**Issue by RagePit** [ProjectOpenSea/seaport#277]
![image](https://user-images.githubusercontent.com/35245632/169591364-79d134e4-5909-4b73-80bc-2a017eb91997.png)
Foundry tests unusable without the optimized bytecode. 
I'd note that something like `FOUNDRY_PROFILE=optimized forge test` or `yarn test:forge` needs to be used instead

**Comment by 0age** [comment]
Thanks! Fixed by https://github.com/ProjectOpenSea/seaport/pull/280
