### ISSUE TITLE
getOrderHash off chain

### ISSUE THREAD

**Issue by hubba-bubba-776** [ProjectOpenSea/seaport#292]
Hey guys, first of all, kudos for open sourcing such a massive protocol!

I want to obtain order hash offline. 

Could you help with that ?

**Comment by Slokh** [comment]
You can use `seaport-js` which we just publicized, relevant code here: https://github.com/ProjectOpenSea/seaport-js/blob/5e51db1a5f42d6c1e16b13c35e7c43d017f70ea1/src/seaport.ts#L445
