### ISSUE TITLE
[docs] request for documentation: lazymint

### ISSUE THREAD

**Issue by TrejGun** [ProjectOpenSea/seaport#303]
Hi guys thanks a lot for outsourcing this massive protocol

as a user, I want to sell items using lazy mint. let's say I have a contract

```
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

contract ERC721ACBR is AccessControl, ERC721 {
  bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
  
  constructor(
    string memory name,
    string memory symbol,
  ) ERC721(name, symbol) {
    _setupRole(DEFAULT_ADMIN_ROLE, _msgSender());
    _setupRole(MINTER_ROLE, _msgSender());
 }

  function mint(address to, uint256 tokenId) public virtual onlyRole(MINTER_ROLE) {
    _mint(to, tokenId);
  }
}
```

now I want to create an order signed by wallet with MINTER_ROLE 
that contains an invocation of `mint(address, uint256)` instead of `transfer(address,address,uint256)`
to sell the not minted items for a fixed price using seaport

**Comment by TrejGun** [comment]
@Slokh please, just a general idea in a few words

**Comment by callum-elvidge** [comment]
Any update on this?

**Comment by TrejGun** [comment]
@callum-elvidge I'll give you a hint, your `zone` should call mint function

**Comment by pranav3714** [comment]
> @callum-elvidge I'll give you a hint, your `zone` should call mint function

Can you give a bit more info on this and also which testcases should I focus on.
