### ISSUE TITLE
[docs] request for documentation: auction

### ISSUE THREAD

**Issue by TrejGun** [ProjectOpenSea/seaport#304]
Please describe the algorithm of how to create an auction using the seaport protocol

as a user, I want to be able to create a store to sell items at auction
I want to be able to set the start and end time of the auction in the future
I want to be able to set a buyout price that ends the auction immediately

How to create an order with date ranges?
How to create an order which will not be filled after the first bet and will accept another bet with a bigger amount
How to set buyout price which will end auction right after fulfillment
How to call seaport from the server when action timed up but the buyout price was not reached

**Comment by psanoy** [comment]
Would just like to ask here as well to request for documentation on setting Royalty fees

**Comment by JasperAlexander** [comment]
> Hey! We will definitely be updating our documentation for specific functionality in the coming weeks. Right now we're just heavily focused on audits and ensuring no vulnerabilities.

How many weeks yet?

**Comment by ad-dev3** [comment]
Looking forward updated documentation. Thanks @Slokh

**Comment by Tointer** [comment]
Is it time for updated documentation yet? Thanks @Slokh

**Comment by TrejGun** [comment]
I guess at this point it is absolutely obvious that the OpenSea team will not provide us with any documentation because of a simple reason - they are going to earn money themself. This means if you are smart enough to understand how it works - use it, otherwise go back to web2.0. Basically, we had the same with the wyvern protocol.

**Comment by vishal590** [comment]
@Slokh Hey bro, can I participate in writing code. I have to gain some exp. please reply, I am waiting for your reply
