### ISSUE TITLE
Collection Offers on api

### ISSUE THREAD

**Issue by shea851** [ProjectOpenSea/seaport#526]
Hi, how are seaport collection offers retrieved for a collection via the API?

- The v2.0 API has an offers endpoint, but it seems to require a token ID with the collection address, and only gives offers specific to that token, not returning "collection-wide" offers.
- The v1.1 API has a single asset offers endpoint, and it does return seaport orders, but none are collection offers.

Thank you much. If this is not the right place to ask this, I apologize. I am not a user of discord so this was the only alternative I could find. Please point me somewhere else if that's where I should go.

**Comment by Slokh** [comment]
Hey! The OpenSea API currently does not support criteria-based orders (i.e collection or attribute offers), when OpenSea does support it, you should hear about it at @apiopensea twitter account
