### ISSUE TITLE
nfts not showing on opensea testnet rinkeby erc721@4.1.0

### ISSUE THREAD

**Issue by muneebsoftblock** [ProjectOpenSea/seaport#570]
opensea https://testnets.opensea.io/assets/rinkeby/0x2301334d923434Ff569ba4fD7FC19C35758086bE/1

rinkeby solidity code https://rinkeby.etherscan.io/address/0x2301334d923434ff569ba4fd7fc19c35758086be#code

nfts were showing in version 3.3.0 erc721a but not on erc721a 4.1.0

**Comment by Slokh** [comment]
This is not relevant to Seaport. Please open a support ticket: support.opensea.io
