### ISSUE TITLE
Purchasing NFTs via mainnet fork leading to revert '815e1d64'.

### ISSUE THREAD

**Issue by TumTum23** [ProjectOpenSea/seaport#589]
We are integrating your marketplace with ours and are facing difficulties when it comes to purchasing listed NFTs. 

We are using data from your API to purchase listed NFTs via a mainnet fork. 

When we try to do so we are receiving the revert code `815e1d64`.

Could you please provide steps explaining how to purchase listed items on Opensea via Seaport.

**Comment by arr00** [comment]
This revert indicates that the signature is invalid as can be seen [here](https://github.com/ProjectOpenSea/seaport/blob/891b5d4f52b58eb7030597fbb22dca67fd86c4c8/contracts/lib/ConsiderationConstants.sol#L386-L389). Ensure that the chain id of the mainnet fork is 1 if trying to simulate mainnet orders.

**Comment by TumTum23** [comment]
Thank you arr00, testing this now.

**Comment by TumTum23** [comment]
Thank you arr00 :)
 
 This has fixed our issue.
 
 Have a good day.
