### ISSUE TITLE
Conduit-Keys

### ISSUE THREAD

**Issue by stefstef800** [ProjectOpenSea/seaport#590]
I noticed little documentation on how to obtain a conduit-key, the only answer I have came across is using the "createConduit" function. How-ever this method requires a conduit key to use, thus not answering the question of how to obtain one

**Comment by arr00** [comment]
We have been shifting questions regarding usage of Seaport to discussions as it is a more appropriate location for them. Please see #544 for the discussion regarding this topic.

**Comment by stefstef800** [comment]
I see, thank you for the clarification!
