### ISSUE TITLE
Question about how to get orderHash when fulfill an order

### ISSUE THREAD

**Issue by y1cunhui** [ProjectOpenSea/seaport#595]
Hi, I'm learning the seaport protocol now, and have some question about how to create an order. 
According to my recent experience in Opensea, if I want to sell an NFT, I just need to sign a message containing the basicOrder data struct(I have approved this collection). There is no on-chain transaction happened, so where is this signature and order information stored? 
When I want to buy an NFT, I just call the fulFillBasicOrder method with proper parameters, but I don't know where the data and signature are stored. Is there a backend on Opensea to store these things?

Thanks!

**Comment by arr00** [comment]
Yes, Opensea stores orders along with the relevant information for Opensea orders. View [Opensea-js](https://github.com/ProjectOpenSea/opensea-js).
