### ISSUE TITLE
How to change the name, bio and banner of a smart contract that holds NFTs?

### ISSUE THREAD

**Issue by Rotemy** [ProjectOpenSea/seaport#599]
Hey guys, probably not the best place to ask this question but I will give it a go as it is extremely hard to reach any Opensea developers.

I've built https://thecollectorsnft.xyz/ which allows you to create Vaults (smart contracts) that buy and sell NFTs on Opensea. For example https://opensea.io/0x1F9538cFF01451BF5e828A4E822872CEbE00D494.

I'm wondering, how can I modify the name, bio and banner of those smart contracts?

**Comment by ryanio** [comment]
You won't be able to customize those fields unless you can log into the account with Metamask. Perhaps in the future there can be some metadata standard to fill in those values from fields from the tokenURI, but for now I don't believe that functionality exists.

**Comment by Rotemy** [comment]
Hi @ryanio thank you for responding.

I remember seeing some smart contract wallets (Gnosis and others) that where able to change the name and icon of their profile, how did they do it?

**Comment by ryanio** [comment]
@Rotemy no problem. I asked re: gnosis wallets collections' and they have to be updated internally manually since they cannot sign into opensea if they're the only owners/editors.

**Comment by Rotemy** [comment]
@ryanio got it, thank you again. On another note that is completely not related to this issue but to be honest I don't know what to do, OpenSea removed the collection of our product https://opensea.io/assets/0xc39b2308BE6B708457ee82Ad35252c0c3C8f0d3B/1 and I don't have any idea why and it really hurting us. It would be amazing if you can reach someone on Opensea about it. I've opened ticket #657495 

I will delete this comment tomorrow to keep this issue clean.

Thank you so much
