### ISSUE TITLE
Validated Listing Not Showing Up on Opensea

### ISSUE THREAD

**Issue by 0xAskar** [ProjectOpenSea/seaport#600]
Hey, 

I've recently been trying to list orders using the `validate` function through seaport-js which just calls the `validate` function in the Seaport contract. However, the order goes through and it is signed, but it does not show up on Opensea. I include the opensea 2.5% and the creator fee for the item as well. Here is the [NFT](https://opensea.io/assets/ethereum/0x569f26145f0c2fcc3da68395be3639009c53b6d8/546) I'm trying to list on opensea, and here's my code:

```
const provider = new ethers.providers.Web3Provider(window.ethereum);
        const seaport = new Seaport(provider);
        let seller = await getBuyer()
        let order = null
        const createListing = async() => {
            // create the order for listing
            const {executeAllActions} = await seaport.createOrder({
                offer: [
                    {
                        itemType: ItemType.ERC721,
                        token: "0x569f26145f0c2fcc3da68395be3639009c53b6d8",
                        identifier: "546"
                    }
                ],
                consideration: [
                    {
                        amount: "93500000000000000",
                        token: "0x0000000000000000000000000000000000000000",
                        recipient: seller //offerer, which is the seller in this case to list it
                    },
                    {
                        amount: "2500000000000000",
                        token: "0x0000000000000000000000000000000000000000",
                        recipient: "0x8De9C5A032463C561423387a9648c5C7BCC5BC90" //offerer, which is the seller in this case to list it
                    },
                    {
                        amount: "4000000000000000",
                        token: "0x0000000000000000000000000000000000000000",
                        recipient: "0xbEb423ffe37c9b63314F5A3043B28D2d8631B4D9" //offerer, which is the seller in this case to list it
                    }
                ],
                zone: "0x004C00500000aD104D7DBd00e3ae0A5C00560C00",
                conduitKey: "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
                zoneHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
                startTime: "0",
                endTime: (Math.floor(new Date().getTime()) + 1*1*60*60*1000).toString(),
            })
            const executedOrder = await executeAllActions()
            order = executedOrder
            const { transact } = seaport.validate([order]);
            const transaction = await transact();
            console.log(transaction)
        }
        await createListing()
  ```

**Comment by ryanio** [comment]
As you discovered through your [solution](https://github.com/ProjectOpenSea/seaport/discussions/594#discussioncomment-3289401) the order would have to be submitted through the opensea listings api. it would be great to ingest validated orders since you wouldn't need an api key but it would be expensive to list them on chain every time.

**Comment by 0xAskar** [comment]
Thanks for the response. However, why would it be expensive to ingest validated orders? Wouldn't Opensea just need to track the validated orders on-chain and then add it to their database?

Also, I know it is expensive to pay using `validate`; however, that is the price to pay to use a decentralized protocol instead of relying on Opensea's API. So, my question is the cost, rather why is Opensea not tracking orders that are validated with the correct Opensea fee and creator fee?

Thanks.

**Comment by ryanio** [comment]
I just meant expensive for the submitter to list them on chain, not expensive for opensea to ingest. It would be great though. possibly the endTime issue might have been part of the problem, I see your code solution had the /1000 division to get from ms to seconds.

**Comment by 0xAskar** [comment]
Ahh I see. Are you then saying that I should list without the /1000 and see if Openseas will catch that? Also, would I be able to list without the /1000 anyways? It seems that with the API and `createOrder`, I need to ensure that its in secs and not ms.

**Comment by ryanio** [comment]
yes it has to be in seconds not ms. you could give it a shot, maybe on the testnet first to see if it might work validating on chain with the parameters you found successful when submitting to the listings api? let me know if you need a testnet NFT I can send you one.

**Comment by FloUz-ai** [comment]
hey @0xAskar did it work for you ?

**Comment by 0xAskar** [comment]
@FloUz-ai at the time it did not. I made the team aware in the Discord, and they said it was an on-going bug. However, prob worth a shot to try now or to ask the team.

**Comment by jamesmccomish** [comment]
Any update on this now that [listings are being ingested](https://twitter.com/Slokh/status/1570211430904864770?s=20&t=9uzSfC9sv0JF9eN9jaUllA)? 

I have a similar question to OP. My order data seems fine when I call `seaport.createOrder`, then I put the response into `seaport.validate`. I get a response from `seaport.validate` and manually submit the transaction from Metamask, and I even see that the hash returned corresponds to a valid order on seaport:

![image](https://user-images.githubusercontent.com/68289880/191776892-58a7be9d-dbe0-4322-a5b3-ae99a62ba8cb.png)

The problem is that the listing does not show up in (Goerli) OpenSea. Has anyone been able to make a listing this way?

**Comment by 0xAskar** [comment]
@jamesmccomish I think it's because Opensea themselves do not track validated listings through Seaport. When you submit a listing through Opensea, they automatically add it their own database through their api which is what you need to do. They **should** be tracking validated listings and its slightly annoying they do not, because they are not enabling users to use Seaport on their own platform.

**Comment by jamesmccomish** [comment]
@0xAskar I think that was the case until last week - if you see the tweet I linked, it suggests that seaport validated orders will show up in the frontend. 

Maybe I am interpreting (or implementing) it wrong, but I checked my tx against the one Kartik linked in that tweet and they are almost identical.

**Comment by 0xAskar** [comment]
Hmm, that's great news as well. I'll take a look and see if it works on my end for the Ethereum network. Maybe, they just don't have it set up for Goerli then?

**Comment by mertcmutlu** [comment]
I have been working on the same thing for quite a while. I think my contract works properly but nothing shows up on OS frontend. I am using polygon mainnet currently but I've also tried with goerli etc. Any updates on the issue?

**Comment by mertcmutlu** [comment]
@0xAskar any updated on the issue? I am still stuck with this :(

**Comment by leeren** [comment]
Same issue here, orders called with `validate` do not show on the OS API

**Comment by ryanio** [comment]
@leeren if you can share your tx hash and on which chain I will try to look it up for you to see if there is any error message on our backend while processing it

**Comment by leeren** [comment]
Hey @ryanio, thanks for helping. Here is the transaction on Goerli: https://goerli.etherscan.io/tx/0x76b77472125114ebfc0ebf3d9bc872f58f13026f6acce820c3f8dcdba59e3485#eventlog

Another view:
https://ethtx.info/goerli/0x76b77472125114ebfc0ebf3d9bc872f58f13026f6acce820c3f8dcdba59e3485/

Validate was successfully called, but we do not see the listing for the validated NFT (id=1):
https://testnets.opensea.io/assets/goerli/0x17d63f4cde0f905eac05253a6129403ea1cd52f9/1

**Comment by ryanio** [comment]
@leeren I would recommend using opensea-js that'll help format the order properly to our rules and you can also submit it on chain from that library as well. 

Here are the logs from our backend for that tx hash:

> OrderValidated: Input data failed to parse for 0x0754862514c5305b3b37bb2dde11d86f4e7d5099 for order 0x30856c7ac6d932a6cdd38bed7e5504482ebcf14fa72b6fd6938d31273323dfd5 for transaction 0x76b77472125114ebfc0ebf3d9bc872f58f13026f6acce820c3f8dcdba59e3485: You have attempted to create an order, but you listed the offerer as: 0x0754862514c5305b3b37bb2dde11d86f4e7d5099 and the recipient of the first consideration item as: 0x4a311575d3dd3e4c70a7c8a3b4c2056e26427dbf - these values should be the same for any order

**Comment by leeren** [comment]
@ryanio Thank you - so this means requiring the consideration item first recipient to be the same as the offerer is an OpenSea marketplace specific constraint, and not a SeaPort one? Is there a place to find all these rules?

**Comment by ryanio** [comment]
Yes it is an OpenSea requirement not Seaport. Unfortunately we don't have one place with ALL the rules BUT if you submit the order via the API you should receive any issues as validation errors. Then if you get a success you should be confident the same order can be sent on chain and picked up by us. If you're still having trouble let me know and I'll try to find the new tx hash. As suggested using opensea-js should help format based on our expectations.

**Comment by ubudragon** [comment]
@ryanio, same issue. could you please help to figure out what the problem is

the order was validated on the BSC testnet but did not show up on Opensea
here is tx: 0xcf62c9c7b1addea35682b914069998b57b3cca3a59bbd4d87cdb19526e7ac871

link:
https://testnet.bscscan.com/tx/0xcf62c9c7b1addea35682b914069998b57b3cca3a59bbd4d87cdb19526e7ac871

PS. Unfortunately, we can not test it with opensea-js, because it just doesn't work with Binance testnet at all =(

**Comment by ryanio** [comment]
@ubudragon bsc is no longer supported on opensea, the chain is still there in "read only" mode but orders cannot be created

**Comment by ubudragon** [comment]
> @ubudragon bsc is no longer supported on opensea, the chain is still there in "read only" mode but orders cannot be created

thanks, @ryanio! 
strange that you decided to abandon BSC, but ok.
all works with Sepolia btw

**Comment by ubudragon** [comment]
There are some troubles still..

if the order consideration consists of only 2 items (recipient and 2.5% Opensea's fee wallet) - all works, 
the listing reflects at Opensea.

but if to add 3rd item to consideration (supposed to be the royalty receiver) - the order validates but does NOT show up at Opensea.
https://sepolia.etherscan.io/tx/0x199b437280c906584e0a67908abb652b3176842839b923d089d00ddb4e2a84d3

any thoughts? @ryanio?
