### ISSUE TITLE
[Question] Can Collection owners customize CriteriaResolver for their own Collections?

### ISSUE THREAD

**Issue by 0xknon** [ProjectOpenSea/seaport#601]
### Are there Custom CriteriaResolver?

Different NFT projects have different utilities. The state of the NFT might be changed between the time of listing and the time of sold. 

For example, BAYC claiming airdrop. 

1. When the owner is listing it, the airdrop hasn't been claimed. 
2. The buyer wants to buy it for the airdrop. Right before the buyer is buying, the owner claimed the airdrop. 
3. So, the state of the NFT is changed, e.g. Right of claiming airdrop.

If collection owner can add the custom CriteriaResolver, or something like that, BAYC can add the `Airdrop claimed` checking to protect buyer from buying state changed NFT.

**Comment by ryanio** [comment]
Currently criteria are created from a set of token ids.

For your example scenario one could build a custom [zone](https://github.com/ProjectOpenSea/seaport/blob/main/docs/ZoneDocumentation.md) to enforce that kind of logic checking during the time of purchase to approve or deny the sale.
