### ISSUE TITLE
[Question] off-chain order book details?

### ISSUE THREAD

**Issue by jamesmorgan** [ProjectOpenSea/seaport#605]
Hi Seaport devs, 

My understand that the "order book" will be maintained by OpenSea in some form and will be "off-chain" - are there any plans to work on a open decentralised off-chain order book of sorts?  I understand that there is also an on-chain engine as well but I suspect the vast majority will use the off-chain matching engine for UX/GAS savings

Please correct me if I am wrong on this front and it works differently?

Thanks

**Comment by ryanio** [comment]
Hey @jamesmorgan, yes we are working on exactly this - a decentralized p2p orderbook for Seaport orders that anyone can spin up a node and listen to orders for interested contracts, or all activity. Hope to have something to show soon, keep an eye out and I will try to remember to ping you when we have a public pre/beta release.

**Comment by jamesmorgan** [comment]
> Hey @jamesmorgan, yes we are working on exactly this - a decentralized p2p orderbook for Seaport orders that anyone can spin up a node and listen to orders for interested contracts, or all activity. Hope to have something to show soon, keep an eye out and I will try to remember to ping you when we have a public pre/beta release.

Thats really great to hear! - looking forward to seeing this in action and building on it
