### ISSUE TITLE
[docs] request for documentation: zones

### ISSUE THREAD

**Issue by mmarkell** [ProjectOpenSea/seaport#607]
Would love to read up on how to deploy a zone with custom validation logic, any example paradigms for constructing zone hashes, etc

**Comment by pistomat** [comment]
This would be really helpful! Meanwhile does anyone know about any deployed opensource zones that are in use?

**Comment by mmarkell** [comment]
@pistomat [Royal](https://royal.io) (where I work) [deployed a zone to Polygon](https://polygonscan.com/address/0xb2f6a627d2a673b81b6be0f57e51c0541368199d) as part of our marketplace.
