### ISSUE TITLE
When creating a mirror order, why filter ERC20 from original Order offer items?

### ISSUE THREAD

**Issue by valerioleo** [ProjectOpenSea/seaport#608]
In the `createMirrorAcceptOfferOrder` function, used to create mirror offers, we remove the Offer items that have `itemType === 1` (which corresponds to ERC20 tokens).
https://github.com/ProjectOpenSea/seaport/blob/fb1c3bf4c25a32ae90f776652a8b2b07d5df52cf/test/utils/fixtures/marketplace.ts#L381

This creates issues when I want to mirror an Order of type:
```js
{
  offer: [anERC721OfferItem],
  consideration: [anERC20ConsiderationItem]
}
```

which gets mirrored into:
```js
{
  offer: [], // <--- now this is empty
  consideration: [anERC721OfferItem] 
}
```

which, when I try to fulfil using the `matchAdvancedOrders` function, it fails with a `InvalidFulfillmentComponentData()` error. 
BUT, if I comment out the line where we remove the ERC20 items, then the Order is matched correctly.

Tbh, I cannot think of a reason why ERC20 items should be removed when mirroring an Order. Am I missing anything?

Thanks!

**Comment by ryanio** [comment]
Not sure, this is a test util so maybe it was doing something specific. You are right that it would not create a valid matched order if it excludes ERC20 items. If you remove that line do any of the tests fail?

If you are looking for a production library then check out https://github.com/ProjectOpenSea/seaport-js
