### ISSUE TITLE
Fulfillment format

### ISSUE THREAD

**Issue by bitcoinben1** [ProjectOpenSea/seaport#644]
Hello i'm trying to develop an aggregator for personal use using directly the seaport contract function matchOrders()
it works great with one item but when i try to submit an order with several items i can't get a proper fulfillments object , i'm on nodejs and using web3.js
example of fulfillments which gives a types/values length mismatch
`const offerComponents = [{
                orderIndex:0,
                itemIndex:0
        },{
                orderIndex:0,
                itemIndex:0
        }];
`
`
        const considerationComponents =[{
                orderIndex:0,
                itemIndex:1
        },{
                orderIndex:0,
                itemIndex:1
        }];
`
`
        const fulfillments = [{
                offerComponents: offerComponents,
                considerationComponents : considerationComponents
        }]
`
vars are hardcoded for test purposes

**Comment by CostofLivingFree** [comment]
Hi Bitcoinben1 - did you find an effective way to do this programmatically by any chance?
