### ISSUE TITLE
can not compile to java use solcjs and web3j

### ISSUE THREAD

**Issue by amazingMan2017** [ProjectOpenSea/seaport#645]
i use solcjs to compile SeaPort.sol to generate abi and bin first

solcjs --optimize --abi --bin Seaport.sol -o  ./build

then i use web3j to compile the abi and bin to java
~/Downloads/web3j-1.4.1/bin/web3j generate solidity -b ./build/Seaport_sol_Seaport.bin -a ./build/Seaport_sol_Seaport.abi -o ./build -p com.test

but error occurs:
              _      _____ _ 
             | |    |____ (_)
__      _____| |__      / /_ 
\ \ /\ / / _ \ '_ \     \ \ |
 \ V  V /  __/ |_) |.___/ / |
  \_/\_/ \___|_.__/ \____/| |
                         _/ |
                        |__/ 
by Web3Labs
Generating com.test.Seaport_sol_Seaport ... not a valid name: struct OrderParameters

is there any way to resolve it ???

**Comment by amazingMan2017** [comment]
additional , i use the branch remotes/origin/seaport-1.1

**Comment by Yjarmouni** [comment]
Hi @amazingMan2017, i get a similar error while trying to compile the contract ( part 'struct ConduitTransfer' is keyword ).

Did you get to compile it somehow ?

Thanks
