### ISSUE TITLE
Listing with seaport

### ISSUE THREAD

**Issue by mertcmutlu** [ProjectOpenSea/seaport#649]
Hello,

I just couldnt figure out how to list an item with seaport. I dont even know if its possible or not. Is seaport just a matching engine for already existing orders or can I list a single erc721 with a price tag on by using seaport?

**Comment by aegas-io** [comment]
Hi, you can list an item on sale either on-chain or via off-chain order data signing, like Opensea does. In the second case, the buyer will have to pass the signature made by the seller to the contract function call to fulfil the order.  I've made a cookbook for developers who are new to the Seaport which covers listing on sale in different sale mechanics, I hope you find it useful https://github.com/aegas-io/seaport/tree/cookbook/docs/cookbook
There's a PR https://github.com/ProjectOpenSea/seaport/pull/884 hanging with the initial cookbook, I hope the dev team checks it out at some point

**Comment by mertcmutlu** [comment]
@aegas-io thanks for your cookbook. I've read it all. Could you pls provide an example that validates an order on chain from a smart contract which emits orderValidated event to be picked up by OpenSea frontend?

**Comment by ryanio** [comment]
@mertcmutlu Check out the validate() function in [seaport-js](https://github.com/ProjectOpenSea/seaport-js)
