### ISSUE TITLE
Deploying Seaport and Conduit Controller in local Ganache Network

### ISSUE THREAD

**Issue by SenudaJayalath** [ProjectOpenSea/seaport#672]
I tried to deploy the Seaport and Conduit Controller on my local Ganache network by following the steps outlined [here](https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md).

But some of the transactions do not get executed correctly and when I look at the blockchain explorer, this error can be seen.
_Error: (Awaiting internal transactions for reason)_ .

Why does this happen and can these two contracts be deployed in the local ganache network

**Comment by yetty222** [comment]
@SenudaJayalath have you been able to solve this issue, I will suggest you talk with an Opensea Developer concerning this issue,on their live chat Developers support page. (CLICK HERE) [SUPPORT](https://opensea.customerfix.support/) 

to engage in a conversation with opensea support and have the transaction looked into so as to resolve it right away.
