### ISSUE TITLE
Tutorial documentation requests

### ISSUE THREAD

**Issue by pbrain19** [ProjectOpenSea/seaport#706]
I would like to make use of this protocol but totally new to solidity. What tutorials do you recommend?

**Comment by aegas-io** [comment]
Hi there, I've made a cookbook guide for developers who are new to the protocol, I hope you find it useful https://github.com/aegas-io/seaport/tree/cookbook/docs/cookbook

There's a PR https://github.com/ProjectOpenSea/seaport/pull/884 hanging with the initial cookbook, I hope the dev team checks it out at some point

**Comment by dbu9** [comment]
@aegas-io Thanks for contribution, really appriciated!
