### ISSUE TITLE
FulFillOrder function not recognizing native token in metamask and throwing error

### ISSUE THREAD

**Issue by neptuneeight** [ProjectOpenSea/seaport#977]
Hi there, I have been trying to use the fulfillorder() function after calling the validate() and putting the order on-chain. (I am not providing a signature since they are put on chain.)

My orders are filled perfectly fine when I only include erc1155 and erc20 tokens, but as soon as I include native token (i'm on polygon so matic), I get thrown an error -32603 metamask error "error reverted" with no further detail.

I have tried this with both using a zone and full restricted order type as well as no zone with full open open order type and I still get this error.

I have also tried to add a gaslimit to the fulfillorder(). If I do this I by pass the initial error and metamask opens for signing, but no matic balance shows up, but I have included some as a consideration, so when I try and fulfill it doesn't go through.

Again, I can transfer as many erc1155 and erc20 tokens as I like with this method (validate on chain and then fulllfill order), but I can't include matic as native token.

Any thoughts or help would be greatly appreciated!

**Comment by ryanio** [comment]
are you sending the matic needed for payment as the value along with the fulfill transaction? also, for the consideration items do you have itemType 0 to mean native token?
